sudo: required
services:
    - docker
env:
    global:
        - SHA=$(git rev-parse HEAD)
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
    - openssl aes-256-cbc -K $encrypted_8ffd329e25b3_key -iv $encrypted_8ffd329e25b3_iv -in travis-sa.json.enc -out travis-sa.json -d
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud components update kubectl
    - gcloud auth activate-service-account --key-file travis-sa.json
    - gcloud config set project udemy-k8s-293622
    - gcloud config set compute/zone europe-north1-a
    - gcloud container clusters get-credentails udemy-k8s
    - echo "$DOCKER_PASSOWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t gaborfeher/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true gaborfeher/react-test npm test

deploy:
    provider: script
    script: bash ./deploy.sh
    on:
        branch: master